import type { Role } from "./types";

export const experience: Role[] = [
  {
    id: "cognizant",
    company: "Cognizant",
    companyUrl: "https://www.cognizant.com",
    title: "Principal AI Consultant / Senior PM",
    client: "Clients: Philips, Rio Tinto, PepsiCo Global, Pearson",
    location: "Sydney",
    start: "Dec 2021",
    end: "Present",
    lede: "Leading AI solution delivery from envisioning through to production. Day to day: architecting Azure-native GenAI applications, running Scaled Agile programmes, and advising Philips, PepsiCo and Pearson on the stack and the ways of working.",
    bullets: [
      "Designed and shipped a RAG pipeline converting QlikSense to PySpark for Philips — 80% reduction in conversion effort across thousands of reports and hundreds of dashboards. Stack: Azure AI Foundry, base LLM + embedding models, vector DB, Python.",
      "Delivered the Azure Foundation Data project for Philips, improving downstream analytics quality and availability by 40%.",
      "Ran SAFe PI Planning and Scrum-of-Scrums across four scrum teams; sprint velocity up 30%.",
      "Spearheaded Stibo MDM implementation at PepsiCo in a waterfall/agile hybrid — 30% reduction in data inconsistencies, 30% faster go-to-market.",
      "Secured $100k+ in project funding and drove 30% YoY cost reduction across the engagement.",
      "Led GCP migration and Tableau dashboards for Pearson's Q-Interactive and Q-Global products.",
      "Designed and delivered a RAG-pipeline training curriculum for 50+ engineers covering Azure AI Foundry, prompt engineering, and LLM deployment.",
    ],
    stack: [
      "Azure AI Foundry",
      "OpenAI",
      "Semantic Kernel",
      "RAG",
      "Python",
      "Databricks",
      "Snowflake",
      "Azure DevOps",
      "SAFe",
      "BigQuery",
      "Tableau",
      "Stibo MDM",
    ],
  },
  {
    id: "capgemini",
    company: "Capgemini",
    companyUrl: "https://www.capgemini.com",
    title: "Project Manager / Senior Business Analyst",
    client: "Client: Volvo Cars",
    location: "Remote, global team",
    start: "Jul 2019",
    end: "Nov 2021",
    bullets: [
      "Led the first-market Salesforce rollout for Volvo Cars India — went from low-probability-of-success to go-live, then +50% sales volume in the first year post-launch.",
      "Pioneered Salesforce CPQ and online configurator implementation during COVID-19, enabling dealerships to take remote orders — business continuity during lockdowns.",
      "Designed custom dashboards and reports (monthly sales, warranty claims, model/variant performance) across 16 dealerships nationwide.",
      "Trained 400+ dealership users on the Salesforce platform, dealer portal, and custom reporting.",
      "Coordinated multinational delivery across Shanghai, Sweden, and India — tight deadlines, minimal rework.",
    ],
    stack: [
      "Salesforce Sales Cloud",
      "Marketing Cloud",
      "CPQ",
      "Business Analysis",
      "Agile",
      "JIRA",
      "Change Management",
    ],
  },
  {
    id: "netsmartz",
    company: "Netsmartz",
    title: "Agile Project Manager / Scrum Master",
    start: "May 2018",
    end: "Jun 2019",
    bullets: [
      "Led a cross-functional team shipping a wearable sleep-quality app for driver safety — 20% reduction in road mishaps for the client.",
      "Designed a custom JIRA workflow for Spraying Systems Co. that delivered a 35% efficiency boost in delivery cadence.",
      "Ran scrum ceremonies (planning, review, retros) for two product teams in parallel.",
    ],
    stack: ["Scrum", "JIRA", "Wearables", "Mobile", "Kanban"],
  },
  {
    id: "bls",
    company: "BLS International",
    title: "Project Coordinator",
    start: "Jul 2016",
    end: "Apr 2018",
    bullets: [
      "PMO lead on the world's largest e-governance ERP implementation — 2000+ centres and a 5000-member team under management.",
      "Owned scheduling, stakeholder cadence, and PMI-standard compliance across a multi-year, multi-geography programme.",
    ],
    stack: ["ERP", "PMO", "MS Project", "Stakeholder Management", "PMI"],
  },
  {
    id: "security-weaver",
    company: "Security Weaver (Pathlock)",
    companyUrl: "https://pathlock.com",
    title: "Technical Product Lead — SAP",
    start: "Jan 2013",
    end: "Mar 2016",
    bullets: [
      "Technical owner for Emergency Repair and Separations Enforcer GRC product lines on SAP NetWeaver.",
      "Pioneered SAP ABAP-on-HANA migration across the full GRC product suite.",
      "Delivered and supported live to Siemens AG, Rolls-Royce, Airbus, Pratt & Whitney, NBC Universal, and Serco.",
      "Owned release documentation, customer scenarios testing, and real-time production support.",
    ],
    stack: ["SAP ABAP", "HANA", "NetWeaver", "GRC", "Smartsheet"],
  },
];
